import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# Hot feature loads read the materialized view (#1082/#1084 P1): feature loading
# becomes an index scan instead of a 7-branch UNION re-derivation (~11.5ms/movie).
# Kept fresh by the daily MaterializedViewRefreshSweeper + explicit refreshes.
config :cinegraph, :metric_values_relation, "metric_values_matview"

# which you should run after static files are built and
# before starting your production server.
config :cinegraph, CinegraphWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # kamal-proxy health-checks /health over plain HTTP. Without excluding it,
  # Plug.SSL 301-redirects the probe to https, the proxy never sees a 2xx, and
  # the container is marked unhealthy and killed (→ Cloudflare 502 with no
  # backend). Excluding the health path lets the probe through while real
  # traffic still gets the HTTPS redirect + HSTS. NOTE: passing :exclude
  # overrides the default, so localhost/127.0.0.1 must be re-listed explicitly.
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    exclude: [hosts: ["localhost", "127.0.0.1"], paths: ["/health"]]
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Cinegraph.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
